envytools/envytools

rnndb/pm/ptherm.xml
this new temperatur sensor allows to read values below 0 ° C. The offset indicates the lowest value possible.
=> ptherm: add new temp regs for GF119-

rnndb/bus/pci.xml
seems to be there since the first PCIe v2.0 card.
also if the UNK1 reg only indicates 5.0, PPCI.CARD_LNK_CTL2 is dropped to 5.0 by the blob (kepler+)
=> rnndb/pci: add reg containing LNK_CTL2 speed

nvbios/nvbios.c
This value needs to be a bit bigger for the voltage because otherweise we would have beend a maximum value of 1048575 uv and this is obviously not enough.
I think that two more bits can be added to that field, but I want to be rather safe here and just add this one bit
=> nvbios: parse the VID entry voltage right for ver 0x50

docs/hw/gpu.rst, nvbios/info.c, nvhw/chipset.c, rnndb/nvchipsets.xml
Not sure if I need to add the chipset somewhere else. Some parts of the VBIOS are not properly parsed:
*   BIT 'i' table has strange size: 0x0046 > 0x0044
*   Unknown IUNK21 table version 1.1
*   Failed to parse IUNK21 table at 0xd4aa version 1.1
*   Unknown POWER BUDGET table version 0x30
*   Unknown CSTEP table version 0x8
*   Unknown UNK3C table version 0x20
*   Unknown DCB table version 4.1
*   Failed to parse DCB table at 0x52d1 version 4.1
Should I attach the fix to this PR, or can it be merged in a second one? (I haven't written the fixes yet.) The VBIOS can be found in the nvidia_vbios repo.
=> nvbios,nvhw,rnndb: Add GM200 chipset

rnndb/bus/pci.xml
this reg seems to indicate the configuration max speed like the 0x88460 reg in pre kepler cards. Also the pcie cap speed can be set with bits 16:17
=> rnndb/pci: add another kepler pcie reg

rnndb/graph/gk104_compute.xml
These commands seem to be only available for GK110+. Note they are already used in the compute support in mesa.
=> rrnd/graph: add some missing unknown bits for GK110_COMPUTE-

nvbios/bios.h, nvbios/power.c, nvbios/print.c
this table seems to hold some base clocks, but currently I can't really figure out when the clocks are used.
The base clock seems to be used when the card is idling, but max performance is prefered (in nvidia-settings)
=> WIP nvbios: fill in unk38 table

rnndb/g80_defs.xml, rnndb/graph/g80_texture.xml, rnndb/graph/gm200_texture.xml
This PR does two things:
1) Update the G80 header documentation to complete them and harmonize the names with NVIDIA's
2) Add the complete documentation for the GM2 texture headers. This new format is the only one recognized by GM200 and later chips.
The renaming of G80 is helpful in that it helps understanding where fields have moved in the new GM2 structures, however it will impact code using the generated headers. If I went too far in the renaming frenzy, please let me know.
Also I am not too sure whether my usage of the inline property in the new enums is correct.
=> Document Maxwell 2's texture headers

nvbios/info.c
Looks like a copy/paste error. It now matches the list at:
http://nouveau.freedesktop.org/wiki/CodeNames
=> nvbios/info: correct chipset for G92

envydis/gm107.c
There is actually three input regs and one output reg.
=> envydis: add missing input reg for lop3 insn on GM107

envydis/gk110.c
I added pdstl_bf which is the same as psrc4_bf, but it seems like it's a better idea to use PDSTL instead of PSRC3 because this predicate is only set if the lock/store has been successfully executed, and PSRC3 doesn't mean the same thing in my opinion.
=> envydis: add ld lock/st unlock on GK110

nva/CMakeLists.txt
I researched this further, when compiled from source python3 by default will only provide a python3-3.5.pc file, although it seems many distros softlink it to python3.pc among another names. It would probably be best to support finding the default python3-3.5.pc file instead of just a softlink to it.
=> Use pkg_search_module() to find the python3 pkgconfig file.

nvbios/nvbios.c
‘for’ loop initial declarations are only allowed in C99 mode
=> nvbios: fix build error

envydis/gm107.c
It would be good to have a second pair of eyes for this really weird SUATOM instruction on SM50+, because I'm not sure if it's *totallly* correct. :-)
=> envydis/gm107: add SUATOM

nva/CMakeLists.txt
This will make the install location of README-nva be consistent with the other documentation when DOC_DIR is set.
=> nva: Fix install directory for README-nva

CMakeLists.txt
If `docs/.gitignore` is removed for some reason configure will break so this will make sure its present before it is removed from `HWDOCS_SRC`.
=> cmake: Don't break on configure if docs/.gitignore is missing

docs/hw/display/nv3/pcrtc.rst, docs/hw/display/nv3/pramdac.rst
This information has been verified by running Quake and a VESA tester on an emulator based on it. 1600x1200 doesn't seem to work based on this however, and the values programmed into the CRTC don't make much sense (1856x1200???). I'm thinking it's a bug in the BIOS I'm using to emulate the NV4.
=> Add some info on the NV3 and NV4's VESA subsystem

nvbios/bios.h, nvbios/nvbios.c, nvbios/power.c, nvbios/print.c
@Lekensteyn has a gm204 with a vbios with 32bit table offsets in some P tables. This PR changes the needed bits to at least parse the vbios right. But there will be much more work if we want to change everything
=> nvbios: 32bit table offsets

docs/envydis/index.rst, envydis/envydis.c
Add documentation to envydis, including missing and incorrectly labelled commands.
Reflect consistent documentation across in line comments and reStructuredText.
=> envydis: Add documentation

docs/hw/gpu.rst
This is the apparently only location that doesn't include Pascal in a descriptive list of GPU families. As this location ends up being presented prominently in the documentation it is worth amending.
=> docs: hw/gpu.rst was missing Pascal

nvbios/nvbios.c
Mirrors change made in the drm kernel driver in February 2016.
```
From 989f57847396d1d042204747985d6aacf5399c8a Mon Sep 17 00:00:00 2001
From: Ben Skeggs <bskeggs@redhat.com>
Date: Thu, 18 Feb 2016 04:03:39 +1000
Subject: [PATCH] drm/nouveau/bios/devinit: rename INIT_DP_CONDITION to
INIT_GENERIC_CONDITION
Signed-off-by: Ben Skeggs <bskeggs@redhat.com>
```
=> nvbios: Rename DP_CONDITION to GENERIC_CONDITION

nvbios/nvbios.c
Brings into consistency with the kernel, which has reflected this two opcodes since:
```
From c79965d8fa275f81af4aa868b01e09c3975127a3 Mon Sep 17 00:00:00 2001
From: Ben Skeggs <bskeggs@redhat.com>
Date: Thu, 21 Aug 2014 08:22:03 +1000
Subject: [PATCH] drm/nouveau/bios: support for opcodes 0x47/0x48
Signed-off-by: Ben Skeggs <bskeggs@redhat.com>
```
=> nvbios: Add support for opcodes 0x47/0x48

demmt/buffer.c
Fixes clang warning:
```
demmt/buffer.c:201:24: warning: comparison of unsigned expression < 0
is always false [-Wtautological-compare]
if (cpu_mapping->id < 0 || get_cpu_mapping(cpu_mapping->id) != cpu_mapping)
~~~~~~~~~~~~~~~ ^ ~
```
=> demmt: Avoid comparison of unsigned expression < 0

nvbios/info.c
VBIOS for the gk208 and gk208b as seen in the wild.
=> nvbios: Add support for gk208 and gk208b

nvbios/info.c
Mislabeling seen in the wild with VBIOS from two GM107s.
Fixes:
```
From 7aef7f84bf9cae61edda12f4dff5ce47724c7fce Mon Sep 17 00:00:00 2001
From: Martin Peres <martin.peres@labri.fr>
Date: Mon, 21 Jul 2014 17:01:46 +0200
Subject: [PATCH] nvbios/info: detect the nve6/nv117
```
=> nvbios/info: Correctly label GM117 (nv117) -> GM107 (nv117)

nvbios/info.c
As a follow up to the request from @imirkin in https://github.com/envytools/envytools/pull/76
=> nvbios/info: Add remainder of known Pascal (nv130) series

nvbios/info.c
Two small cleanups for `nvbios/info`:
* Correct code comment about GM206 (nv126)
* Add support for GM108 (nv118)
=> Two nvbios/info cleanups

cupti_trace/cupti_make_report.py, rnn/renouveau2rnn, rnn/rules2rnn, rnn/text2xml, rnn/xml2text
Enhance portability by using $PATH to locate `python3` and `python` executables, rather than hardcoded locations.
=> Fix python env invocation for better portability

nvbios/mem.c, nvbios/nvbios.c
Benefits from:
```
From 4766ec53945f14f134fc51de782b362a51351cb1 Mon Sep 17 00:00:00 2001
From: Ben Skeggs <bskeggs@redhat.com>
Date: Tue, 4 Nov 2014 12:06:25 +1000
Subject: [PATCH] drm/nouveau/bios: add parsing of BIT M(v2) +0x03 table
We only support one kind of matching here (ramcfg strap), but it appears
alternate methods are possible.  I wrote a tool to scan our vbios repo
for other types, but did not see any used.  Hopefully this means there
aren't any in the wild that will now break.
Signed-off-by: Ben Skeggs <bskeggs@redhat.com>
```
=> nvbios: Add unknown mem types for Pascal and "skip"

envydis/gk110.c
According to nvdisasm $sr80 and $sr81 are SR_CLOCKLO and SR_CLOCKHI
respectively. $sr82 and $sr83 are SR_GLOBALTIMERLO and SR_GLOBALTIMERHI.
=> gk110: Fix definition of clock and globaltimer special registers

rnndb/graph/gf100_3d.xml
Found with the trace from https://trello.com/c/kuMPh88f , verified
working in WIP for ARB_post_depth_coverage implementation:
https://github.com/Lyude/mesa/tree/wip/gm200-ARB_post_depth_coverage
Signed-off-by: Lyude <lyude@redhat.com>
=> gf100: Add POST_DEPTH_COVERAGE register to database

rnndb/graph/gf100_pgraph/gpc.xml, rnndb/graph/gf100_pgraph/tpc.xml
On Pascal now reports completely for gr SLCG:
```
PGRAPH.DISPATCH.HW_BLK.SLCG <= 0
PGRAPH.CTXCTL.UNK17C <= 0x20008
PGRAPH.CTXCTL.HW_BLK.SLCG <= 0x40
PGRAPH.TPBUS.HW_BLK.SLCG <= 0
PGRAPH.UNK6000.HW_BLK0.SLCG <= 0
PGRAPH.UNK5800.HW_BLK.SLCG <= 0
PGRAPH.UNK5900.HW_CGBLK.SLCG <= 0xfffffff0
PGRAPH.CCACHE.HW_BLK.SLCG <= 0
PGRAPH.SKED.HW_BLK.SLCG <= 0
PGRAPH.GPC_BROADCAST.CTXCTL.UNK17C <= 0x20008
PGRAPH.GPC_BROADCAST.CTXCTL.HW_BLK.SLCG <= 0x40
PGRAPH.GPC_BROADCAST.UNK500.HW_CGBLK.SLCG <= 0
PGRAPH.GPC_BROADCAST.UNK600.HW_BLK.SLCG <= 0
PGRAPH.GPC_BROADCAST.UNK680.HW_BLK.SLCG <= 0
PGRAPH.GPC_BROADCAST.UNK700.HW_BLK.SLCG <= 0
PGRAPH.GPC_BROADCAST.UNK380.SLCG <= 0
PGRAPH.GPC_BROADCAST.ESETUP.HW_CGBLK.SLCG <= 0
PGRAPH.GPC_BROADCAST.TPBUS.HW_BLK.SLCG <= 0
PGRAPH.GPC_BROADCAST.ZCULL.HW_BLK.SLCG <= 0 …
```
=> rnndb/graph/slcg: Document missing SLCG (Second Level Clock Gating) registers

rnndb/bus/pmc.xml
Based in part upon [0] and IRC discussion November 22, 2017.
[0] https://download.nvidia.com/open-gpu-doc/pascal/1/gp100-msi-intr.txt
=> rnndb/pmc: Document PVDEC bitfield of PMC.{ENABLE|INTR_*}

rnndb/bus/pmc.xml
Based in part upon [0] and IRC discussion November 22, 2017.
[0] https://download.nvidia.com/open-gpu-doc/pascal/1/gp100-msi-intr.txt
=> rnndb/pmc: Document PSEC2 bitfield of PMC.{ENABLE|INTR_*}

hwtest/pgraph_class_kelvin.cc, hwtest/pgraph_state_tests.cc
Fixes two categories of warnings picked up by CI.
C++11 added `override` to ensure member functions you write where you intend to override base-class virtual functions actually do.
Picked up by `-Winconsistent-missing-override` warning present in Clang 3.5 and higher. GCC 5.1 has a similar `-Wsuggest-override`.
=> Fix override of base-class provided virtual functions in hwtest

cgen/.gitignore
Used to ignore locally-generated output files in cgen.
Fixes: 9e6b83e5 ("Single Source of Truth.")
=> cgen: Add .gitignore

CMakeLists.txt, cgen/CMakeLists.txt, cupti_trace/CMakeLists.txt, demmt/CMakeLists.txt, easm/CMakeLists.txt, envydis/CMakeLists.txt, envydis/test/CMakeLists.txt, hwtest/CMakeLists.txt, nva/CMakeLists.txt, nvbios/CMakeLists.txt, nvhw/CMakeLists.txt, rnn/CMakeLists.txt, util/CMakeLists.txt, vdpow/CMakeLists.txt, vstream/CMakeLists.txt, vstream/test/CMakeLists.txt
envytools since 7e2e2e9a has required `cmake` 3.5 at a minimum. Let's be explicit about this minimum supported version via cmake's own dependency checking functionality.
Whilst changes in easm -- specifically to `FindFLEX` module `FLEX_TARGET` -- bumped the cmake requirement to 3.5, given easm is not optional let's just bump the cmake requirement across the tree. Most major distributions currently ship cmake 3.9+.
Fixes: 7e2e2e9a ("easm: Fix compilation in directories with space in name.")
=> cmake: Explicit on minimum version required

rnndb/bus/pci.xml
nvgpu documents that writing a dummy value 0 to this register rearms PCI MSI on Pascal.
=> rnndb/pci: Document Pascal PCI MSI rearm register (CYA_2)

rnndb/memory/gf100_pbfb.xml, rnndb/memory/gf100_pmfb.xml, rnndb/memory/gf100_pxbar.xml
These are all of the slcg registers I've found thus-far that weren't
already documented in rnndb that I've come across in the vbios repo. As
well, the sources I used to verify each as much as possible:
Confirmed in android tegra repos:
- 0x17e050
- 0x17ea98
- 0x13cc04 (this also made it obvious that 0x13cc00 exists beyond the
GK104)
Confirmed in nvidia nvgpu repos:
- 0x13c824
Guesses based off nearby register writes:
- 0x10f280
The value of all of these registers is consistently 0x0, however that
seems to match up perfectly with the production values specified in
android's tegra drivers and nvgpu, with the disable value being
non-zero (0x0 must be some sort of enable I suppose).
=> rnndb: Add more missing registers for GK110+

nvbios/power.c
Taken from
http://download.nvidia.com/open-gpu-doc/BIOS-Information-Table/1/BIOS-Information-Table.html
=> nvbios/power: Add missing POWER TOPOLOGY table name usage

nva/nvapy.pyx
NvaCard_.endian (0 = little-endian, 1 = big-endian)
=> nva/nvapy: Expose endian type to Python module

rnndb/graph/gf100_3d.xml
Adds subpixel precision bias for conservative rasterization like in GL_NV_conservative_raster.
=> rnndb/graph: add subpixel precision bias for conservative raster

rnndb/graph/gf100_3d.xml
It seems SUBPIXEL_PRECISION is meant to be per-viewport.
=> make SUBPIXEL_PRECISION per-viewport

nvbios/CMakeLists.txt, nvbios/bios.h, nvbios/bit.c, nvbios/nvbios.c, nvbios/p.c, nvbios/power.c, nvbios/print.c
Document within envytools a better understanding of BIT_TOKEN_FALCON_DATA('p') within the VBIOS.
This series adds:
* Support for the VBIOS BIT('p') version 2 table; and
* Ability to extract Falcon processor (PMU) ucode found in the VBIOS.
*Note*: The working understanding is that the PMU ucode(s) are bootloader, code and data loaded onto the PMU early during POSTing the card. For example, one of the "application_id"s handles limited, interim fan management. This isn't the full firmware ucode loaded subsequently by the blob.
The new output can be produced with `./nvbios/nvbios -p p <path_to_vbios>`. Add `-v` to increase verbosity and to extract the PMU ucode(s).
=> nvbios: BIT('p')v2 / Falcon processor (PMU) ucode

nvbios/bios.h, nvbios/d.c, nvbios/print.c
Document in envytools our better understanding of BIT_TOKEN_DP_PTRS('d') within the vbios.
In particular, this decodes or locates:
* DisplayPort (DP) link training, speed change and spread scripts & configuration data;
* GPU registers used to enable support for various DP functionality;
* HBR3 functionality introduced with Pascal.
The new output can be produced with `./nvbios/nvbios -p d <path_to_vbios>`. Add `-v` to increase verbosity.
Thanks to Nvidia for releasing documentation!
=> nvbios: DisplayPort / BIT('d') improvements

nvbios/T.c, nvbios/bios.h, nvbios/print.c
Points to TMDS Info table that relates to Transition-minimized Differential Signaling (TMDS)
which is a technology for transmitting high-speed serial data, incorporating an advanced
coding algorithm which reduces electromagnetic interference over copper cables and enables
robust clock recovery at the receiver.
Utilized by DVI and HDMI video interfaces, amongst others.
Based on: https://download.nvidia.com/open-gpu-doc/BIOS-Information-Table/1/BIOS-Information-Table.html#_bit_tmds_ptrs
=> nvbios/T: Use 'TMDS Info Table' for first entry in BIT 'T' table

nvbios/nvbios.c
Tested on 3x GV100 VBIOSes, each of which are known to have HBM2 memory.
Unable to validate against a Tesla GP100, which is the only other known NVIDIA card with HBM2 at this time -- but confident this is correct.
=> nvbios: Add HBM2 memory type, present on GV100 GPUs

README.rst, nva/CMakeLists.txt
As discussed in #130 and #118:
`cython3` required as nva/nvapy requires `python3` as a minimum dependency.
Cmake gracefully falls back to `cython` for distributions that have not renamed the built executable that provides Python 3 support.
=> nva/nvapy: Improve nva documentation

rnndb/display/g80_pdisplay.xml
rnndb/disp/g80:
- Add recent display classes for GM200, GP100 and GP102
- Rename CLASS to CLASS_ID
Sources:
https://download.nvidia.com/open-gpu-doc/Display-Class-Methods/2/README.txt
https://download.nvidia.com/open-gpu-doc/Display-Ref-Manuals/1/gv100/dev_display.ref
=> Improve PDISPLAY FE_CLASSES

rnndb/display/g80_pdisplay.xml
Improvements to missing bitfield entries in:
* NV_PDISP_SOR_CAP(i)
* NV_PDISP_SOR_PWR(i)
* NV_PDISP_SOR_DP_LINKCTL(i,j)
Document DisplayPort Test Pattern Group (TPG):
* NV_PDISP_SOR_DP_TPG(i,j)
Source: https://download.nvidia.com/open-gpu-doc/Display-Ref-Manuals/1/gv100/dev_display.ref
=> rnndb/pdisp: Improve PDISPLAY SOR and DisplayPort TPG documentation

envydis/gm107.c
Previously, the sign bit for various immediate operands was kept as a separate flag. This changes the immediate operands so that the sign bit is part of them, making both disassembled binaries and gm107.c clearer.
Assembly created by or meant for older versions of envyas/envydis may be compatible after this, but I don't think that's much of a concern.
=> envydis/gm107: merge various sign bit flags with their operands

envydis/gm107.c
It probably isn't at bit 35, since the immediate uses that bit. Messing around with nvdisasm, it seems you can't specify the flag for immediate operands.
=> envydis/gm107: Remove h1 flag for immediate operand of xmad

rnndb/memory/gf100_pbfb.xml
Pascal and later generations had changes to framebuffer partition addressing (FBPA).
```
These MMIO ranges have been moved and expanded from 0x1000 to 0x4000 in size:
Name                Old Range               New Range
NV_PFB_FBPA         0x10F000 (0x1000)       0x9A0000 (0x4000)
NV_PFB_FBPA[i]      0x110000+(i * 0x1000)   0x900000+(i * 0x4000)
NV_PFB_FBPA_MC[i]   0x11D000+(i * 0x1000)   0x980000+(i * 0x4000)
The number of NV_PFB_FBPA[i] ranges is increased to a maximum of 16.
The number of NV_PFB_FBPA_MC[i] ranges remains 3.
Memory partition sizing and programming is the same as in prior NVIDIA
architectures.
```
Reflect these changes within rnndb.
Source:
https://download.nvidia.com/open-gpu-doc/pascal/1/gp100-fbpa.txt
https://nv-tegra.nvidia.com/gitweb/?p=linux-nvgpu.git;a=blob;f=driv …
=>  rnndb/memory/gf100_pbfb: Support Pascal framebuffer partition addressing changes

docs/hw/graph/maxwell/cuda/index.rst, docs/hw/graph/maxwell/cuda/int.rst, docs/hw/graph/maxwell/cuda/isa.rst, docs/hw/graph/maxwell/index.rst
This isn't really something meant to be complete, but to document instructions with behaviour not obvious from reading envydis/gm107.c (such as iadd3, xmad and maybe texture instructions).
Currently, it just documents iadd3 and xmad.
=> hwdocs/maxwell: add initial CUDA ISA docs with iadd3 and xmad

rnndb/falcon.xml, rnndb/graph/gf100_pgraph/ctxctl.xml
A set of improvements to ctxsw microcode support ported from `nvgpu`.
On my Pascal this just about covers all previously unknown ctxsw registers utilized by the blob.
v2: Reflects changes suggested by @koriakin
=> Improve ctxsw microcode support (FECS and GPCCS) v2

envydis/gm107.c
with one of the dest being zero we get different color masks.
=> envydis/gm107: add 1 and 2 component color masks to texs and tlds

rnndb/graph/gf100_pgraph/ctxctl.xml
This covers all possible Front-End Context Switch ("FECS") method commands that the blob utilizes on my Pascal.
These *might* enable context switching instrumentation in later families, similar to: https://www.repository.cam.ac.uk/bitstream/handle/1810/277888/rtgpu-preempt.pdf?sequence=3
=> rnndb: Add Front-End Context Switch ("FECS") method adr commands

docs/envydis/index.rst, envydis/falcon.c, rnndb/falcon.xml
Falcon version 6 has been seen on some Pascal-series engines (`PVDEC`, `PVENC`, `PSEC2` and `PGRAPH.CTXCTL`).
For now, note this within documentation and prepare the necessary bitfields for future support for any fuc6+ opcodes that might be encountered.
=> Preliminary Falcon v6 documentation support

docs/hw/falcon/io.rst, rnndb/falcon.xml
envytools presently has two sources of Falcon hardware registers:
* docs/hw/falcon/io.rst
* rnndb/falcon.xml
Whilst the naming of registers doesn't need to exactly match for historical reasons, over time documented registers have at times been added to one and not the other -- so conform any missing registers from either documentation into the other.
=> Falcon documentation: Conform both hw docs to each other

envydis/gm107.c
20 bits doesn't make much sense: it would overlap with other atoms.
Seems it's 16 bits without a sign flag.
=> envydis/gm107: Make xmad's immediate 16 bits

demmt/nvrm_decode_mthd.c, demmt/nvrm_mthd.h
Method reports number of available, linked GPUs. On systems with multiple physical GPUs, where SLI is disabled, the method will return a count of 1.
=> demmt: Support NVRM_MTHD_DEVICE_GET_NUM_SLI_GPUS (0x00800280)

nvhw/chipset.c
Fixes compiler warning (clang, version 5.0.0):
```bash
/home/travis/build/envytools/envytools/nvhw/chipset.c:114:16: warning: comparison of constant -1 with expression of type 'enum gpu_index' is always true [-Wtautological-constant-out-of-range-compare]
if (info->gpu != -1) {
~~~~~~~~~ ^  ~~
```
=> nvhw: Fix enum gpu_index comparison with constant -1 (tautological out of range comparison)

docs/hw/pciid.rst
Manually sourced from bbswitch and Bumblebee issue trackers (issues
1-169 and 600-972 respectively, searching for "10de:").
__
Why stop at 600? It became boring...
=> hwdocs/pciid: add various Kepler and Maxwell variants

nvbios/bios.h, nvbios/conn.c
USB Type-C connectors have been added to Turing GPUs.
This output may be utilized for next-generation Virtual Reality headsets.
=> nvbios/conn: Add USB Type-C connector type

nvbios/bios.c, nvbios/bios.h, nvbios/print.c
This series reflects cleanups and improvements to the PCI Expansion ROM parsing against current specifications. Some highlights:
* Fully document Legacy and EFI PCI Expansion ROM and PCIR Data Structure (pcir) fields.
* Support changes introduced with PCI Specification 3.0+.
* Support EFI PCI Expansion ROM headers (e.g. multi-part VBIOS').
* Better report Intel x86 PC-AT, OpenFirmware, and EFI code types; improve validation; and better track used blocks.
As an example, the output changes on a multi-part (Intel x86 PC-AT compatible and EFI) VBIOS are:
```diff
$ diff -u vbios.txt.before vbios.txt.after 
--- vbios.txt.before	2018-11-24 21:34:40.009202055 -0500
+++ vbios.txt.after	2018-11-24 21:34:29.437135750 -0500
@@ -23,19 +23,26 @@
BIOS size 0x20400 [orig: 0x100000], 2 valid parts:
BIOS …
```
=> nvbios: PCI Expansion ROM parsing improvements

nvbios/bios.c, nvbios/bios.h, nvbios/bit.c
Version field of BIT Header is actually 16 bits, with the major version in the upper byte, minor version in the lower byte.
Until now, envytools was only reading the major version number.
Verified no other output of `nvbios` changed:
```diff
$ diff -u vbios.txt.before vbios.txt.after 
--- vbios.txt.before	2018-11-24 12:39:00.830658504 -0500
+++ vbios.txt.after	2018-11-24 12:39:30.486864194 -0500
@@ -36,7 +36,7 @@
Subsystem id: 0x0000:0x0000
-BIT table at 0x0210 version 1
+BIT table at 0x0210 version 1.0
BIT table '2' version 1 at 0x0292 length 0x0004
BIT table 'B' version 2 at 0x029e length 0x0025
BIT table 'C' version 2 at 0x02c3 length 0x001c
```
=> nvbios/bit: Correct size of BIT Header version field to 16-bits

nvbios/nvbios.c
Two BIOS devinit opcodes that were introduced with Pascal:
* **0x9e**: UNK9E: Single byte, no parameters.
* **0xac**: UNKAC: Seen operating on PFUSE.FUSES+0xb1c and PFUSE.FUSES+0x2f4. Examples below with the inferred structure of the register and (mask, value) pair.
```
UNKAC	R[0x0213f4] = 0x00000001, 0x00000001
...
UNKAC	R[0x021c1c] = 0x00000000, 0xffffffff
```
Verified with NV132, NV134, NV136, NV137 and NV138. No prior occurrences of these two opcodes within the vbios corpus repository.
=> nvbios: Add Pascal family devinit opcodes

nvbios/nvbios.c
During the last refactoring of this function to parse the VOLTAGE MAP TABLE, the parameter c2 was never recorded. Instead the previous c1 value was overwritten.
Noticed whilst reviewing this code for upcoming changes. Verified against the nouveau kernel code.
An example before/after fixed output from an NVCF vbios:
```diff
$ openssl sha256 nvcf/mwk/vbios.rom
SHA256(nvcf/mwk/vbios.rom)= e020fa7e2fdca5e84ee22a2c57deb85489bf77aa04d2cd8ef4bd8b6406d52fe0
$ diff -u /tmp/v1.txt /tmp/v2.txt 
--- /tmp/v1.txt	2019-06-04 23:09:57.234220569 +1000
+++ /tmp/v2.txt	2019-06-04 23:10:50.864455474 +1000
@@ -8,7 +8,7 @@
-- ID = 1, voltage_min = 950000, voltage_max = 950000, volt = 950000 [µV]
0x000066c5: f0 7e 0e 00 f0 7e 0e 00 60 f5 90 00 00 00 00 00 00 00 00 00
--- ID = 2, voltage_min = 1012500, …
```
=> nvbios/perf: Fix overwritten parameter c1 in VOLTAGE MAP TABLE v10

nvbios/nvbios.c
Set NVVDD depending on the VDT entry.
This opcode invokes the PMU to set the NVVDD (voltage for the GPU) depending on the VDT table entry that is passed.
Source:
- https://download.nvidia.com/open-gpu-doc/Devinit/1/devinit.xml#INIT_VDT
=> nvbios: Document INIT_VDT devinit opcode (0xAA)

nvbios/nvbios.c
This series adds support to nouveau for two opcodes seen on VBIOSes prior to the locked-down PMU taking over responsibility for executing devinit scripts.
=> nvbios: Document INIT_RESET_BEGUN and INIT_RESET_END

nva/nva.c
In glibc, limits.h is included in nva.c though stdlib.h. However, on musl, that is not the case. Due to this, compilation on musl fails due to PATH_MAX not being found. This commit adds the relevant include declaration.
=> nva: Compile on musl

rnndb/graph/gf100_3d.xml
This is used by [GL_NV_viewport_swizzle](https://www.khronos.org/registry/OpenGL/extensions/NV/NV_viewport_swizzle.txt) on Nvidia's OpenGL driver, [VK_NV_viewport_swizzle](https://github.com/KhronosGroup/Vulkan-Docs/blob/master/appendices/VK_NV_viewport_swizzle.txt) on Vulkan and by the respective proprietary API function.
Credits go to gdkchan from [Ryujinx](https://github.com/Ryujinx/Ryujinx/) for finding this.
=> rnndb: document viewport swizzles on gm204

envydis/falcon.c
As documented on Switchbrew (https://switchbrew.org/w/index.php?title=TSEC#sigauth & https://switchbrew.org/w/index.php?title=TSEC#sigclr)
=> envydis: Add sigclr and sigauth support

docs/hw/pciid.rst
At some point nVidia released a TU104 based RTX 2060. https://en.wikipedia.org/wiki/GeForce_20_series#Chipset_table
Update pciid.rst to reflect that.
=> Add TU104 based GeForce RTX 2060

demmt/mmt_bin2dedma.c, demmt/mmt_bin2dedma.h, include/var.h
GCC 10 defaults to -fcommon, so it is no longer allowed to put non
extern variable declarations in .h files otherwise we get linker
errors about conflicting symbols in the .o files.
This commit fixes these linking errors.
=> Fix compilation with gcc10 which defaults to -fcommon

demmt/mmt_bin2dedma.c
Reverts envytools/envytools#201
As said in [this comment](https://github.com/envytools/envytools/pull/201#issuecomment-623635859) - similar fix has already landed and github CI failed to detect it.
Pardon for the breakage.
=> Revert "Fix compilation with gcc10 which defaults to -fcommon"

nvbios/nvbios.c
Forces the Memory Information Table entry look-up.
This function forces the init processor to execute entry look-up in the Memory Information Table, which includes reading Memory Strap and/or Memory ID from hardware registers and searching for the matching entry. The memory information is then cached for fast retrieval in subsequent operations.
Upon return from the Memory Information Table entry look-up, the devinit engine continues processing.
This opcode allows for clear indication of when to read the Memory Strap and Memory ID registers, which may be manipulated by other devinit opcodes, so that all engines can be instructed to process the Memory Information Table in an identical sequence.
Present on [core70,)
Source:
- https://download.nvidia.com/open-gpu-doc/Devinit/1/devinit.xml#INIT …
=> nvbios: Document INIT_MEM_INFO devinit opcode (0x9E)

nvbios/nvbios.c
Post PMU taking over responsibility for interpreting devinit scripts, these are helpful to debug VBIOSes. 
However, nouveau currently has no need to interpret these directly nor is a method currently known to modify devinit scripts in VBIOSes in a way that allows modified versions to be loaded by the PMU.
This series adds all devinit opcodes verified as present within a corpus of Volta and Turing GPUs.
=> nvbios: Document / parse Volta & Turing devinit opcodes

rnndb/graph/g80_2d.xml
Update rnndb with documented Nvidia cl902d.h (NVC0_2D) mthd `NVC0_2D_SET_DST_COLOR_RENDER_TO_ZETA_SURFACE`.
This is sourced from:
- https://github.com/NVIDIA/open-gpu-doc/blob/master/classes/twod/cl902d.h
And was already manually added by bskeggs to the otherwise autogenerated
header file in mesa:
- https://gitlab.freedesktop.org/mesa/mesa/-/commit/af3c2f3cfd81186b0041e5297db5225fc788b04e
=> Add NVC0_2D_SET_DST_COLOR_RENDER_TO_ZETA_SURFACE mthd

rnndb/graph/g80_2d.xml
Update rnndb with documented Nvidia cl502d.h (NV50_2D) mthd `NV502D_SET_PIXELS_FROM_MEMORY_SAFE_OVERLAP`.
This is sourced from:
- https://github.com/NVIDIA/open-gpu-doc/blob/master/classes/twod/cl502d.h
=> Add NV50_2D_SET_PIXELS_FROM_MEMORY_SAFE_OVERLAP mthd

rnndb/fifo/gk104_copy.xml, rnndb/nv_defs.xml
Has been utilised within nouveau in place of the former `M2MF` class, which was dropped for Kepler in `PGRAPH` in favour of:
- a new `P2MF` object that only does simple upload; and
- `PCOPY` took over responsibility of `M2MF`'s other DMA functions.
NVIDIA documentation released at:
https://github.com/NVIDIA/open-gpu-doc/blob/master/classes/dma-copy/cla0b5.h
=> Add NVE4 (Kepler) DMA COPY class documentation

demmt/drm.c
NOUVEAU_GETPARAM_(FB|AGP|PCI)_PHYSICAL doesn't exist anymore in newer
versions of libdrm, so let's drop the references to this in order to fix
compilation.
Signed-off-by: Lyude Paul <lyude@redhat.com>
=> demmt: Fix compilation errors from removed nouveau params

envydis/gm107.c
Add LDG variant with a predicate, for example:
```
LDG.U8 P0, R0, [RZ];  /* 0xeec80e000007ff00 */
```
It is likely this predicate is used to return the sparse status of a memory page, similar to TEX when used on sparse textures. Although I'm not familiar with any public API that allows querying the sparse state of a memory page. ARB_sparse_buffer doesn't define any shader changes, but I haven't checked if the blob uses it with that extension + robustness to manually zero out uncommitted results.
I'm not happy on how this commit adds the inverted predicates used by this LDG variant. 0 maps to PT, 1 to P6, 2 to P5..., the opposite of the rest of the ISA :D
It's a table with all predicates defined:
```c
static struct insn tabeec8_0[] = {
{ 0x00000e0000000000ull, 0x00000e0000000000ull, …
```
=> envydis/gm107: add ldg variant with predicate

vstream/h264_print.c
Found a tiny, tiny bug while using the parser as reference
H.264 printer prints the modification_of_pic_nums_idc opcode twice in place of the pic_num delta it operates on
=> vstream: fix h264 ref reorder list print error
