rnndb/fifo/g80_pfifo.xml, rnndb/fifo/gf100_pfifo.xml
=> rnndb: de-UNK a few pfifo regs

nva/README
description for more tools and more options in nva.
=> nva README updated.

CMakeLists.txt, cupti_trace/CMakeLists.txt, cupti_trace/cupti_trace.c, cupti_trace/cupti_trace_path.h.in
No problems with licences/copyrights this time. :-)
=> add cupti_trace, a new tool for REing performance counters

rnndb/display/g80_pdisplay.xml, rnndb/display/nv_evo.xml, rnndb/memory/g80_vm.xml, rnndb/nv_defs.xml
This is most likely not the final version and documentation for the other EVO channels are missing, but I'd like to get some feedback already about the form.
=> rnndb/display/evo: Fill core channel documentation

demmt/drm.c, nvbios/mem.c
I'd appreciate a second pair of eyes on trivial changes like this. Thanks!
Signed-off-by: Roy Spliet <rs855@cam.ac.uk>
=> Fix build warnings on 32-bit systems

nva/nva.c
=> nva: fix memory leak

nvbios/info.c
VBIOS for the gm204 as seen in the wild: https://bugs.freedesktop.org/show_bug.cgi?id=89664
=> nvbios: Add support for gm204

.travis.yml, README.rst, nva/CMakeLists.txt
Configure, build and run test suite on GCC and Clang.
=> test: Add Travis-CI continuous integration

README.rst
Small tweaks:
* Help new developers by linking to, and providing status of, envytools' ecosystem resources.
* Improve readability of the reStructuredText README header.
=> Improve README (Travis-CI and RTD)

docs/envydis/index.rst, envydis/envyas.c, envydis/envydis.c
Includes documentation that will make its way to readthedocs
=> envyas: Document the command line for envyas

rnn/fp.py, rnn/headergen.py, rnn/lookup.py, rnn/rnncheck.py, rnn/rnndec.py
Fixes:
* Undefined variable error in `rnn/rnndec.py`
* A few simple pylint warnings
=> Fix pylint error and warnings

nva/.gitignore
=> nva: Add missing binary files to .gitignore

docs/hw/memory/pbfb.rst, docs/hw/memory/pmfb.rst
noticed with inspection going through the documentation.
=> hwdocs: make the {front,middle,back} memory controller usage consistent

.travis.yml, Dockerfile
I don't want to comment on that....
=> travis: silly workaround for travis-ci/travis-ci #5821

nva/nvagetbios.c
Just some improvements to nvagetbios to save myself some typing, and hopefully make things a bit easier for users. Includes autodetection for whether to use PROM/PRAMIN, and automatic extraction of strap_peek
=> nvagetbios improvements

nvhw/chipset.c
So: this check is right for basically every card under the sun except
some rather weird ones. Turns out one of these weird ones is the
GK208B/NV108 (GT710) that I got in the mail, which appears to have a
PMC.ID value of 0xb060b0b1. This seems to be one of the rare cases
(which strangely is actually mentioned in the comments for nva already)
where both bits 31 and 7 are set to 1.
So: we know a couple of things now:
- Pre-NV10: B31 and B7 are always 0
- NV10+ LE: B31 is 0, B7 is 1 OR
B31 is 1 and B7 is 1, and B8-11 are 0
- NV10+ BE: B31 is 1, B7 is 0 OR
B31 is 1 and B7 is 1, and B16-19 are 0
So, use this to come up with a better algorithm for detecting this
that's still valid across multiple generations. Now we can handle my
weird card :).
=> nva: Fix pmc_id endianness check

demmt/object_state.c, demmt/pushbuf.c, rnndb/fifo/nv_object.xml
Source:
https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=6e1f34e33c17f633ebbd383cab429c820ec0c7b0
=> demmt: Add preliminary VOLTA_DMA_COPY support

demmt/nvrm_decode_ioctl.c, demmt/nvrm_ioctl.h
Complete documentation of the NVRM ioctl's I've seen on Pascal.
=> demmt: nvrm ioctls v2

docs/hw/pciid.rst
Just conforming against NVIDIA Driver README and pci-ids database.
=> docs/hw/pciid: Add various Pascal and Turing variants

demmt/object_gk104_3d.c, envydis/gm107.c
found today:
MUFU.SQRT R22, R22;                                                 /* 0x5080000000871616 */
=> add mufu.sqrt for GM200+
